### ISSUE TITLE
Error trying to use with R-3.4.0 for Windows

### ISSUE THREAD

**Issue by jimmywan** [holgerbrandl/r4intellij#100]
I installed the 64-bit executable (omitted the 32-bit executable) and configured it to point to:
`<install dir>/bin/R.exe`

```
Failed to generate skeleton for 'translations'. The error was:

Error in library(package = pName, character.only = TRUE) : 
  package 'translations' does not have a namespace and should be re-installed
Execution halted


If you think this issue with plugin and not your R installation, please file a ticket under https://github.com/holgerbrandl/r4intellij/issues


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by holgerbrandl** [comment]
`translations` is now excluded from indexing. Please update and try again.
