### ISSUE TITLE
Failed to generate skeleton for 'translations'

### ISSUE THREAD

**Issue by geniusjiqing** [holgerbrandl/r4intellij#107]
Failed to generate skeleton for 'translations'. The error was:

Error in library(package = pName, character.only = TRUE) : 
  package 'translations' does not have a namespace and should be re-installed
Execution halted

If you think this issue with plugin and not your R installation, please file a ticket under https://github.com/holgerbrandl/r4intellij/issues

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
`translations` is now excluded from indexing since it does not contain any methods anyway.
