### ISSUE TITLE
Write access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by geniusjiqing** [holgerbrandl/r4intellij#113]
Write access is allowed from event dispatch thread only
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@96372d Current thread: Thread[ApplicationImpl pooled thread 141,4,Idea Thread Group] 24887059 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1.2#IU-145.972.3 IDEA, eap:false, os:Windows 7 6.1, java-version:Oracle Corporation 1.8.0_77-b03,6,main] 27098676

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1115)
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:1222)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1007)
	at com.r4intellij.settings.LibraryUtil.createLibrary(LibraryUtil.java:34)
	at com.r4intellij.interpreter.SkeletonUpdater.runActivity(SkeletonUpdater.java:34)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:149)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:60)
	at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:167)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:163)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:164)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:157)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$5.run(ProjectManagerImpl.java:387)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
Thanks for reporting the issue. Is there a way to reproduce it?

**Comment by holgerbrandl** [comment]
Closed due to missing user feedback
