### ISSUE TITLE
Failed to generate a valid skeleton for 'base'

### ISSUE THREAD

**Issue by arthur-st** [holgerbrandl/r4intellij#120]
Windows 7 x64, IDEA 2017.2.1, R 3.4.1.

```
Failed to generate a valid skeleton for 'base'. Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:248)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by arthur-st** [comment]
Running skeletonize_package.R against base works fine and results in a base.skeleton.R, which though gets rejected by the plugin, even after it is renamed, and the plugin just indexes base again on startup, and fails, deleting the custom skeleton.

**Comment by arthur-st** [comment]
R 3.4.1 was x64, and the problem repeated itself with R 3.4.0 and R 3.3.3 too.

**Comment by holgerbrandl** [comment]
Some users suggested that this may be related to the used version of R
> I can confirm changing from R 3.4.1 to 3.3.3 also fixed this issue for me.

**Comment by gzrcm** [comment]
@holgerbrandl, I switched to R 3.3.1 as you suggested in #118. I now get the following error: 

Failed to generate a valid skeleton for 'base'.helperOutputNull=false

**Comment by hughstimson** [comment]
I have the same issue, with all R versions I've tried (so far R 3.4.1, 3.3.3 and 3.2.5, x64 in all cases). Windows 10, IntelliJ 2017.2.4 and Pycharm 2017.1.3.

**Comment by tchakravarty** [comment]
Windows 7 x64, IDEA 2017.1, R 3.3.2. Same issue.

**Comment by jgoodman8** [comment]
I got the same issue: 

`Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Any idea how to solve it? The other packages goes well.... so its a pitty

**Comment by rwatts3** [comment]
I'm too having this issue and have had it for nearly a year now. Any pointers on how we can help resolve this would be great.

IT's a critical piece of the plugin, seeing as though the base skeleton contains majority of what most users will be working with in regards to intellisense. If we don't have them, it sort of makes the plugin useless and I would hate to see that for such a great plugin.

**Comment by borisevichdi** [comment]
Had the problem with R-3.4.3, Windows 10 in PyCharm (several last versions).
Deleted R and made clean installation of last R version (R-3.5.1) to the folder, which name does not have any white-space or "dash" or "dot" symbols (C:\R351\ instead of C:\Program Files\R\R-3.4.3\), and the problem was resolved (no idea, though, whether changing path helped).

**Comment by holgerbrandl** [comment]
Thanks @borisevichdi for the pointer. So maybe it's the whitespaces in the path which cause all this confusion?
