### ISSUE TITLE
Failed to generate a valid skeleton for 'base'.helperOutputNull=false

### ISSUE THREAD

**Issue by dbonner** [holgerbrandl/r4intellij#124]
I am using R-portableapps 3.4.1 using the 32-bit R.exe as the interpreter when I get this error.  I ticked the option to resolve variables  in all modules.  The 64-bit R.exe does not cause an error.  However I need to run this at work where I can only run portable apps on 32-bit machines.
Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 8 6.2
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pbackx** [comment]
I have the same issue. This is not a portable install, but I do not have admin rights on my machine, so maybe there's some commonality there?

Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 7 6.1
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rusa-sarka** [comment]
I have the same issue (R-3.4.1 64-bit):

Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by slava-tsarev** [comment]
same issue, R-3.4.1\bin\x64\R.exe, Windows 7, Intellij IDEA 2017.2.5

Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 7 6.1
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RobustCoder** [comment]
I am seeing a similar issue as everyone else in this thread, altho my error message is slightly different than some people (details below).

It was triggered just now when I updated IntelliJ from 2017.2.? to 2017.3.

I hope that it gets fixed ASAP.

Is there any work around in the meantime?

OS = Win 7 64 bit Pro
JDK = 1.8.0_152
R = 4.4.1 64 bit

Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 7 6.1
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable: Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 7 6.1
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
Looks like the same problem to me. Thanks for reporting it anyway.

**Comment by sriharisahu** [comment]
PyCharm 2017.3.2 (Community Edition)
Build #PC-173.4127.16, built on December 19, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

R Interpreter - C:\Program Files\R\R-3.4.3\bin\R.exe
Python Interpreter - C:\Users\srihari.sahu\AppData\Local\Continuum\anaconda3\python.exe

Steps : 

1. clone git@github.com:tensorflow/models.git 
2. Go to models/tutorials/image/imagenet
3. Run classify_image.py

Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable: Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tghunt** [comment]
R 3.4.4
IntelliJ latest release

java.lang.Throwable: Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
Thanks for reporting the issue. It could be due to user-stats, but It seems to me that this is a windows-specific problem.
