### ISSUE TITLE
Actual type is not the same as expected: [actual: RESPONSE]

### ISSUE THREAD

**Issue by Mincol** [holgerbrandl/r4intellij#139]
```
Actual type is not the same as expected: [actual: RESPONSE, expected: [CONTINUE_TRACE, DEBUG_AT, DEBUGGING_IN, EMPTY, EXITING_FROM, RECURSIVE_EXITING_FROM]]
com.r4intellij.debugger.exception.RUnexpectedExecutionResultTypeException: Actual type is not the same as expected: [actual: RESPONSE, expected: [CONTINUE_TRACE, DEBUG_AT, DEBUGGING_IN, EMPTY, EXITING_FROM, RECURSIVE_EXITING_FROM]]
	at com.r4intellij.debugger.function.RFunctionDebuggerBase.advance(RFunctionDebuggerBase.java:112)
	at com.r4intellij.debugger.RDebugger.continueDebug(RDebugger.java:197)
	at com.r4intellij.debugger.RDebugger.advance(RDebugger.java:115)
	at com.r4intellij.run.debug.RDebugProcess.advance(RDebugProcess.java:299)
	at com.r4intellij.run.debug.RDebugProcess.access$100(RDebugProcess.java:41)
	at com.r4intellij.run.debug.RDebugProcess$1.run(RDebugProcess.java:149)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by holgerbrandl** [comment]
What did you do to cause the error?

**Comment by Mincol** [comment]
I was debugging my R script.

**Comment by Mincol** [comment]
This is minimal example which will reproduce it: `cat("This will create exception")`

So you need additional info?

**Comment by holgerbrandl** [comment]
No, same with me.

**Comment by daimingzhong** [comment]
I have the same problem with 2017.2.3 pycharm. Is it caused by the latest version of Jetbrain?
Could it be fixed by using the older one?

**Comment by holgerbrandl** [comment]
Unfortunately, the R debugger was never ready for primetime imho. But for sure Intellij API is evolveing as well.
