### ISSUE TITLE
IntelliJ IDEA hangs on idexing

### ISSUE THREAD

**Issue by CrazyCoder** [holgerbrandl/r4intellij#141]
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.processEntries(OrderEnumeratorBase.java:294)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEach(ModuleOrderEnumerator.java:47)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.forEach(OrderEnumeratorBase.java:329)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEach(ModuleOrderEnumerator.java:32)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.a(ProjectRootManagerComponent.java:247)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.a(ProjectRootManagerComponent.java:235)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.addRootsToWatch(ProjectRootManagerComponent.java:141)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.b(ProjectRootManagerImpl.java:398)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:42)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:102)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:336)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.a(ModuleManagerImpl.java:929)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1400(ModuleManagerImpl.java:63)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.a(ModuleManagerImpl.java:839)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1200(ModuleManagerImpl.java:619)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:610)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:50)
	at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.commitModel(ModuleRootManagerImpl.java:172)
	at com.intellij.openapi.roots.impl.RootModelImpl.commit(RootModelImpl.java:390)
	at com.intellij.openapi.roots.IdeaModifiableModelsProvider.commitModuleModifiableModel(IdeaModifiableModelsProvider.java:51)
	at com.r4intellij.settings.LibraryUtil$1.run(LibraryUtil.java:72)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.r4intellij.settings.LibraryUtil.createLibrary(LibraryUtil.java:34)
	at com.r4intellij.interpreter.SkeletonUpdater.runActivity(SkeletonUpdater.java:34)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:176)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:162)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$1003/1055989483.run(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:182)
	at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$1008/1310449483.run(Unknown Source)
	at com.intellij.openapi.project.DumbServiceImpl.c(DumbServiceImpl.java:299)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$2626/1242272044.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.c(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.TransactionGuardImpl$$Lambda$2385/1792832759.run(Unknown Source)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

**Comment by holgerbrandl** [comment]
Is there any way to reproduce the issue? Like a specific project setup or something similar.

**Comment by zagorulkinde** [comment]
Hello! Also the issue:

`

> Failed to generate skeleton for 'tcltk'. The error was:
> 
> Error: package or namespace load failed for ‘tcltk’:
>  .onLoad failed in loadNamespace() for 'tcltk', details:
>   call: fun(libname, pkgname)
>   error: Tcl/Tk support is not available on this system
> In addition: Warning message:
> S3 methods ‘as.character.tclObj’, ‘as.character.tclVar’, ‘as.double.tclObj’, ‘as.integer.tclObj’, ‘as.logical.tclObj’, ‘as.raw.tclObj’, ‘print.tclObj’, ‘[[.tclArray’, ‘[[<-.tclArray’, ‘$.tclArray’, ‘$<-.tclArray’, ‘names.tclArray’, ‘names<-.tclArray’, ‘length.tclArray’, ‘length<-.tclArray’, ‘tclObj.tclVar’, ‘tclObj<-.tclVar’, ‘tclvalue.default’, ‘tclvalue.tclObj’, ‘tclvalue.tclVar’, ‘tclvalue<-.default’, ‘tclvalue<-.tclVar’, ‘close.tkProgressBar’ were declared in NAMESPACE but not found 
> Execution halted
> 
> 
> If you think this issue with plugin and not your R installation, please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:236)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

`

and the second issue:

`

> Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
> Details: Current thread: Thread[ApplicationImpl pooled thread 22,4,Idea Thread Group] 1381478063
> ; dispatch thread: false; isDispatchThread(): false
> SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.1.5#IU-171.4694.70 IDEA, eap:false, os:Mac OS X 10.13.2, java-version:JetBrains s.r.o 1.8.0_112-release-736-b21,6,main] 1879099987
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1068)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:152)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
> 	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
> 	at com.r4intellij.psi.references.RResolver.getTrimmedFileName(RResolver.java:364)
> 	at com.r4intellij.packages.PackageServiceUtilKt$rebuildIndex$1.run(PackageServiceUtil.kt:89)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1068)
> 	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:132)
> 	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:110)
> 	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:77)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:156)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
> 	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
> 	at com.r4intellij.psi.references.RResolver.getTrimmedFileName(RResolver.java:364)
> 	at com.r4intellij.packages.PackageServiceUtilKt$rebuildIndex$1.run(PackageServiceUtil.kt:89)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1068)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:152)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
> 	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
> 	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:133)
> 	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:110)
> 	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:77)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:156)
> 	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
> 	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
> 	at com.r4intellij.psi.references.RResolver.getTrimmedFileName(RResolver.java:364)
> 	at com.r4intellij.packages.PackageServiceUtilKt$rebuildIndex$1.run(PackageServiceUtil.kt:89)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

`
