### ISSUE TITLE
failed to split package-version in line 'WARNING: ignoring environment value of R_HOME'.

### ISSUE THREAD

**Issue by SarumObjects** [holgerbrandl/r4intellij#148]
failed to split package-version in line 'WARNING: ignoring environment value of R_HOME'.
 Helper output was:
WARNING: ignoring environment value of R_HOME
BH	1.65.0-1
Cairo	1.5-9
DBI	0.7
DT	0.4
Formula	1.2-2
Hmisc	4.1-1
KernSmooth	2.23-15
MASS	7.3-48
MBESS	4.4.3
Matrix	1.2-12
MatrixModels	0.4-1
OpenMx	2.8.3
PKI	0.1-5.1
PMXStan	0.11
R6	2.2.2
RColorBrewer	1.1-2
RCurl	1.95-4.10
RJSONIO	1.3-0
RMySQL	0.10.13
RUnit	0.4.31
Rcpp	0.12.15
RcppArmadillo	0.8.300.1.0
RcppEigen	0.3.3.3.1
Rttf2pt1	1.3.5
SparseM	1.77
StanHeaders	2.17.2
XML	3.98-1.9
abind	1.4-5
acepack	1.4.1
arm	1.9-3
assertthat	0.2.0
backports	1.1.2
base	3.4.1
base64enc	0.1-3
bayesplot	1.4.0
bindr	0.1
bindrcpp	0.2
bitops	1.0-6
boot	1.3-20
brew	1.0-6
caTools	1.17.1
car	2.1-6
checkmate	1.8.5
class	7.3-14
cli	1.0.0
cluster	2.0.6
coda	0.19-1
codetools	0.2-15
colorspace	1.3-2
colourpicker	1.0
commonmark	1.4
compiler	3.4.1
cowplot	0.9.2
crayon	1.3.4
crosstalk	1.0.0
curl	3.1
data.table	1.10.4-3
datasets	3.4.1
deSolve	1.20
desc	1.1.1
devtools	1.13.4
dichromat	2.0-0
digest	0.6.15
doBy	4.5-15
dplyr	0.7.4
dygraphs	1.1.1.4
evaluate	0.10.1
extrafont	0.17
extrafontdb	1.0
foreign	0.8-69
formatR	1.5
formattable	0.2.0.1
ggplot2	2.2.1.9000
git2r	0.21.0
glue	1.2.0
grDevices	3.4.1
graphics	3.4.1
grid	3.4.1
gridExtra	2.3
gsl	1.9-10.3
gtable	0.2.0
gtools	3.5.0
hexbin	1.27.2
highr	0.6
hms	0.4.1
htmlTable	1.11.2
htmltools	0.3.6
htmlwidgets	1.0
httpuv	1.3.5
httr	1.3.1
iDoseAdalimumabRAv2	0.2.2
iDoseInfliximabUCv1	0.1.5
iDoseProxyContainer	0.1.01
idoseproxy	0.0.13
igraph	1.1.2
inline	0.3.14
irlba	2.3.2
jsonlite	1.5
knitr	1.19
labeling	0.3
lattice	0.20-35
latticeExtra	0.6-28
lavaan	0.5-23.1097
lazyeval	0.2.1
lme4	1.1-15
logging	0.7-103
loo	1.1.0
lubridate	1.7.1
magrittr	1.5
markdown	0.8
matrixStats	0.53.0
matrixcalc	1.0-3
memoise	1.1.0
methods	3.4.1
mgcv	1.8-23
mi	1.0
mime	0.5
miniUI	0.1.1
minqa	1.2.4
mlxR	3.2.0
mnormt	1.5-5
mrgsolve	0.8.10
munsell	0.4.3
mvtnorm	1.0-7
nlme	3.1-131
nloptr	1.0.4
nnet	7.3-12
numDeriv	2016.8-1
openssl	1.0
packrat	0.4.8-1
parallel	3.4.1
pbivnorm	0.6.0
pbkrtest	0.4-7
pillar	1.1.0
pkgconfig	2.0.1
plogr	0.1-1
plotly	4.7.1
plyr	1.8.4
purrr	0.2.4
quadprog	1.5-5
quantreg	5.35
readr	1.1.1
reshape	0.8.7
reshape2	1.4.3
rhandsontable	0.3.6
rlang	0.1.6
rmarkdown	1.8
roxygen2	6.0.1
rpart	4.1-12
rpf	0.56
rprojroot	1.3-2
rsconnect	0.8.5
rstan	2.17.3
rstantools	1.4.0
rstudioapi	0.7
scales	0.5.0.9000
sem	3.1-9
semTools	0.4-14
shiny	1.0.5
shinydashboard	0.6.1
shinyjs	1.0
shinystan	2.4.0
shinythemes	1.1.1
snow	0.4-2
snowfall	1.84-6.1
sourcetools	0.1.6
spatial	7.3-11
splines	3.4.1
stats	3.4.1
stats4	3.4.1
stringi	1.1.6
stringr	1.2.0
survival	2.41-3
tcltk	3.4.1
threejs	0.3.1
tibble	1.4.2
tidyr	0.8.0
tidyselect	0.2.3
tools	3.4.1
utf8	1.1.3
utils	3.4.1
viridis	0.5.0
viridisLite	0.3.0
whisker	0.3-2
withr	2.1.1
xml2	1.2.0
xtable	1.8-2
xts	0.10-1
yaml	2.1.16
zoo	1.8-1

java.lang.RuntimeException: failed to split package-version in line 'WARNING: ignoring environment value of R_HOME'.
 Helper output was:
WARNING: ignoring environment value of R_HOME
BH	1.65.0-1
Cairo	1.5-9
DBI	0.7
DT	0.4
Formula	1.2-2
Hmisc	4.1-1
KernSmooth	2.23-15
MASS	7.3-48
MBESS	4.4.3
Matrix	1.2-12
MatrixModels	0.4-1
OpenMx	2.8.3
PKI	0.1-5.1
PMXStan	0.11
R6	2.2.2
RColorBrewer	1.1-2
RCurl	1.95-4.10
RJSONIO	1.3-0
RMySQL	0.10.13
RUnit	0.4.31
Rcpp	0.12.15
RcppArmadillo	0.8.300.1.0
RcppEigen	0.3.3.3.1
Rttf2pt1	1.3.5
SparseM	1.77
StanHeaders	2.17.2
XML	3.98-1.9
abind	1.4-5
acepack	1.4.1
arm	1.9-3
assertthat	0.2.0
backports	1.1.2
base	3.4.1
base64enc	0.1-3
bayesplot	1.4.0
bindr	0.1
bindrcpp	0.2
bitops	1.0-6
boot	1.3-20
brew	1.0-6
caTools	1.17.1
car	2.1-6
checkmate	1.8.5
class	7.3-14
cli	1.0.0
cluster	2.0.6
coda	0.19-1
codetools	0.2-15
colorspace	1.3-2
colourpicker	1.0
commonmark	1.4
compiler	3.4.1
cowplot	0.9.2
crayon	1.3.4
crosstalk	1.0.0
curl	3.1
data.table	1.10.4-3
datasets	3.4.1
deSolve	1.20
desc	1.1.1
devtools	1.13.4
dichromat	2.0-0
digest	0.6.15
doBy	4.5-15
dplyr	0.7.4
dygraphs	1.1.1.4
evaluate	0.10.1
extrafont	0.17
extrafontdb	1.0
foreign	0.8-69
formatR	1.5
formattable	0.2.0.1
ggplot2	2.2.1.9000
git2r	0.21.0
glue	1.2.0
grDevices	3.4.1
graphics	3.4.1
grid	3.4.1
gridExtra	2.3
gsl	1.9-10.3
gtable	0.2.0
gtools	3.5.0
hexbin	1.27.2
highr	0.6
hms	0.4.1
htmlTable	1.11.2
htmltools	0.3.6
htmlwidgets	1.0
httpuv	1.3.5
httr	1.3.1
iDoseAdalimumabRAv2	0.2.2
iDoseInfliximabUCv1	0.1.5
iDoseProxyContainer	0.1.01
idoseproxy	0.0.13
igraph	1.1.2
inline	0.3.14
irlba	2.3.2
jsonlite	1.5
knitr	1.19
labeling	0.3
lattice	0.20-35
latticeExtra	0.6-28
lavaan	0.5-23.1097
lazyeval	0.2.1
lme4	1.1-15
logging	0.7-103
loo	1.1.0
lubridate	1.7.1
magrittr	1.5
markdown	0.8
matrixStats	0.53.0
matrixcalc	1.0-3
memoise	1.1.0
methods	3.4.1
mgcv	1.8-23
mi	1.0
mime	0.5
miniUI	0.1.1
minqa	1.2.4
mlxR	3.2.0
mnormt	1.5-5
mrgsolve	0.8.10
munsell	0.4.3
mvtnorm	1.0-7
nlme	3.1-131
nloptr	1.0.4
nnet	7.3-12
numDeriv	2016.8-1
openssl	1.0
packrat	0.4.8-1
parallel	3.4.1
pbivnorm	0.6.0
pbkrtest	0.4-7
pillar	1.1.0
pkgconfig	2.0.1
plogr	0.1-1
plotly	4.7.1
plyr	1.8.4
purrr	0.2.4
quadprog	1.5-5
quantreg	5.35
readr	1.1.1
reshape	0.8.7
reshape2	1.4.3
rhandsontable	0.3.6
rlang	0.1.6
rmarkdown	1.8
roxygen2	6.0.1
rpart	4.1-12
rpf	0.56
rprojroot	1.3-2
rsconnect	0.8.5
rstan	2.17.3
rstantools	1.4.0
rstudioapi	0.7
scales	0.5.0.9000
sem	3.1-9
semTools	0.4-14
shiny	1.0.5
shinydashboard	0.6.1
shinyjs	1.0
shinystan	2.4.0
shinythemes	1.1.1
snow	0.4-2
snowfall	1.84-6.1
sourcetools	0.1.6
spatial	7.3-11
splines	3.4.1
stats	3.4.1
stats4	3.4.1
stringi	1.1.6
stringr	1.2.0
survival	2.41-3
tcltk	3.4.1
threejs	0.3.1
tibble	1.4.2
tidyr	0.8.0
tidyselect	0.2.3
tools	3.4.1
utf8	1.1.3
utils	3.4.1
viridis	0.5.0
viridisLite	0.3.0
whisker	0.3-2
withr	2.1.1
xml2	1.2.0
xtable	1.8-2
xts	0.10-1
yaml	2.1.16
zoo	1.8-1

	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:158)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:159)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:55)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:106)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:154)
	... 16 more

**Comment by holgerbrandl** [comment]
It should be more robust against this warning. As a workaround you could `unset RHOME` in your bash-profile. See https://stackoverflow.com/questions/6395078/rscript-get-rid-of-warning-ignoring-environment-value-of-r-home

**Comment by holgerbrandl** [comment]
Some consider it even an R platform bug, see https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=15070

**Comment by SarumObjects** [comment]
Thanks Holger
That resolved the error report. The plugin is a help as I don’t want to switch to RStudio or StatET as I’m using Intellij mostly now
John
