### ISSUE TITLE
Failed to generate a valid skeleton for 'base'.helperOutputNull=false

### ISSUE THREAD

**Issue by luiscm** [holgerbrandl/r4intellij#154]
Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable: Failed to generate a valid skeleton for 'base'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
See http://holgerbrandl.github.io/r4intellij/faq.html#r4intellij-fails-to-index-package-xy-what-canshould-i-do about how to provide a more detailed error report. Thanks!
