### ISSUE TITLE
Ctrl-Q reporting "cannot fetch remote documentation: internal error"

### ISSUE THREAD

**Issue by latinostats** [holgerbrandl/r4intellij#159]
Hello @holgerbrandl 
trying to use the tooltip and only getting "cannot fetch remote documentation internal error" 
any help will be appreciated

![capture](https://user-images.githubusercontent.com/23467752/39503187-820b69ee-4d92-11e8-9ed7-31bd2e0aabd7.PNG)

**Comment by holgerbrandl** [comment]
Is it the same after restarting intellij and trying again?

Can you run a local r help webserver? You can test this with
```r
options(help_type = "html")
?list.files
```

**Comment by latinostats** [comment]
Hi @holgerbrandl 
it is the same after restarting IntelliJ
I run the local web server and the code provided works...
not sure what else to try..
any help will be appreciated... using IntelliJ 2017.3.2

**Comment by holgerbrandl** [comment]
Is there a corresponding stacktrace in the idea.log?

**Comment by latinostats** [comment]
@holgerbrandl .. yes there is!

2018-05-07 22:26:22,487 [ 483088]   INFO - 4intellij.packages.RHelperUtil - Failed to run start help-server 
2018-05-07 22:26:23,487 [ 484088]   INFO - mentation.DocumentationManager -  
java.lang.AssertionError
	at com.r4intellij.documentation.RDocumentationProvider.generateDoc(RDocumentationProvider.java:203)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.lambda$getDocumentation$2(DocumentationManager.java:1139)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.codeInsight.documentation.QuickDocUtil.runInReadActionWithWriteActionPriorityWithRetries(QuickDocUtil.java:96)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.getDocumentation(DocumentationManager.java:1136)
	at com.intellij.codeInsight.documentation.DocumentationManager.lambda$doFetchDocInfo$7(DocumentationManager.java:727)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:242)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
Could you check that your R interpreter is defined an a valid executable? 
![image](https://user-images.githubusercontent.com/200952/39780021-51e7b028-530b-11e8-93f7-1ddfd1195878.png)

If so,  does the following print a port in R `cat( tools::startDynamicHelp(start = TRUE)); Sys.sleep(3600)`?

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen the ticket if the problem remains.
