### ISSUE TITLE
`Fatal error: can't find file` Exception on IDE start up

### ISSUE THREAD

**Issue by azder** [holgerbrandl/r4intellij#167]
Using WebStorm 2018.1 and 2018.2 EAP

```
failed to split package-version in line 'Fatal error: no fue posible abrir el archivo '-f': No such file or directory'.
 Helper output was:
Fatal error: no fue posible abrir el archivo '-f': No such file or directory

java.lang.RuntimeException: failed to split package-version in line 'Fatal error: no fue posible abrir el archivo '-f': No such file or directory'.
 Helper output was:
Fatal error: no fue posible abrir el archivo '-f': No such file or directory

	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:158)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:160)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:55)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:107)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4815)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:154)
	... 16 more
```

**Comment by holgerbrandl** [comment]
Do you have R installed and in your path? If so, which version?
