### ISSUE TITLE
Failed to generate a valid skeleton for 'oce'.helperOutputNull=false

### ISSUE THREAD

**Issue by elalaouifaris** [holgerbrandl/r4intellij#173]
I just installed the R plugin and have this issue reported:
(I'm new to PyCharm sorry if this is a trivial matter)

java.lang.Throwable: Failed to generate a valid skeleton for 'oce'.helperOutputNull=false
skeletonFile_exists=false
isComplete=false
isCurrentSkelVersion=false
OS=Windows 10 10.0
 Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rjcantrell** [comment]
I have the same issue on the same OS, and receive the same error message from RSkeletonGenerator, except with the "base" package. In the "r_skeletons" folder, an empty file named ".base.failed" exists, although skeleton generation seems to have succeeded for other packages (boot, class, cluster, codetools, datasets, graphics, &c.)

This causes functions in the base package (such as "set.seed()" and "c()") to be marked as unresolved references.
