### ISSUE TITLE
rmarkdown file throws exception as soon as opened:

### ISSUE THREAD

**Issue by quantitative-technologies** [holgerbrandl/r4intellij#177]
I just tried out this plugin on a short *.Rmd file, and received 12 error messages. Here is the stacktrace of the first:

`java.lang.Throwable: Failed to generate skeleton for 'car'. The error was:

Error: package or namespace load failed for ‘car’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘nnet’
Execution halted

If you think this issue with plugin and not your R installation, please file a ticket under https://github.com/holgerbrandl/r4intellij/issues

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by holgerbrandl** [comment]
In an R shell, can you load the package with
```
require(car)
```
without any problems?
