### ISSUE TITLE
Cannot run program "/usr/local/lib/R": error=13, Permission denied

### ISSUE THREAD

**Issue by kauedb** [holgerbrandl/r4intellij#184]
When I write some R code using pycharm plugin the following exception is issued:

java.lang.Throwable: Cannot run program "/usr/local/lib/R": error=13, Permission denied
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.r4intellij.packages.RHelperUtil.runHelperWithArgs(RHelperUtil.java:100)
	at com.r4intellij.packages.RHelperUtil.getHelperOutput(RHelperUtil.java:66)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:145)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:160)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:55)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:107)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I tried to change the folder permissions but the issue keeps on.

**Comment by kauedb** [comment]
I forgot to mention that I am using pycharm professional 2018.3.2

**Comment by holgerbrandl** [comment]
Do you have execute permissions on the executable?
