### ISSUE TITLE
Debug Exception - debug not running?

### ISSUE THREAD

**Issue by clFaster** [holgerbrandl/r4intellij#185]
When I try to run my R Script in debug mode, I get an exception in Pycharm:

> com.r4intellij.debugger.exception.RUnexpectedExecutionResultTypeException: Actual type is not the same as expected: [actual: RESPONSE, expected: DEBUG_AT]
	at com.r4intellij.debugger.executor.RExecutorUtils.execute(RExecutorUtils.java:20)
	at com.r4intellij.debugger.function.RFunctionDebuggerBase.initCurrentLine(RFunctionDebuggerBase.java:148)
	at com.r4intellij.debugger.function.RFunctionDebuggerBase.<init>(RFunctionDebuggerBase.java:61)
	at com.r4intellij.debugger.function.RBraceFunctionDebugger.<init>(RBraceFunctionDebugger.java:19)
	at com.r4intellij.debugger.function.RFunctionDebuggerFactoryImpl.getFunctionDebugger(RFunctionDebuggerFactoryImpl.java:37)
	at com.r4intellij.debugger.RDebugger.prepareDebug(RDebugger.java:185)
	at com.r4intellij.debugger.RDebugger.advance(RDebugger.java:113)
	at com.r4intellij.run.debug.RDebugProcess.advance(RDebugProcess.java:299)
	at com.r4intellij.run.debug.RDebugProcess.access$100(RDebugProcess.java:41)
	at com.r4intellij.run.debug.RDebugProcess$4.run(RDebugProcess.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

After that debuging stucks, I didn't get any console output etc. When I run the same script in RUN mode it works fine.

My Code:

```
message("[ADA] starting ..")

library(getPass)
user.name <- getPass(msg = "Enter Username: ", noblank = TRUE, forcemask = TRUE)
user.pw <- getPass(msg = "Enter Password: ", noblank = TRUE, forcemask = TRUE)
```

**Comment by HIJackone** [comment]
i meet this bug too
