### ISSUE TITLE
Is it possible to use radian instead of r console

### ISSUE THREAD

**Issue by reddy-ia** [holgerbrandl/r4intellij#198]
[Radian](https://github.com/randy3k/radian) is an alternative to R console which is colorful similar to ipython.

I tried to change R interpreter path to point it to radian, but it threw an error when I tried to start R console
```radian: error: no such option: --ess```

Looks like radian accepts option `--quiet` but doesn't accept `--ess`. 
![image](https://user-images.githubusercontent.com/52095862/60157159-c34a4f00-980b-11e9-896a-a1562f919ca9.png)

**Is it possible to turn off the option `--ess` when starting r terminal.**

**Comment by holgerbrandl** [comment]
Cool shell, did not know about it. 

To see how it would like in the R Console in Intellij, I've temporarily removed the `--ess` and  configured it to use `radian` instead. However, it fails with

```
Traceback (most recent call last):
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\eventloop\context.py", line 88, in get
    return self._storage[ctx]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\output\defaults.py", line 52, in get_default_output
    value = _default_output.get()
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\eventloop\context.py", line 90, in get
    raise TaskLocalNotSetError
prompt_toolkit.eventloop.context.TaskLocalNotSetError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\brandl\AppData\Local\Continuum\anaconda3\Scripts\radian.exe\__main__.py", line 9, in <module>
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\radian\__init__.py", line 75, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\radian\radianapp.py", line 84, in run
    self.session = create_radian_prompt_session(options)
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\radian\prompt.py", line 226, in create_radian_prompt_session
    mode_class=RadianMode
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\prompt.py", line 79, in __init__
    super(ModalPromptSession, self).__init__(*args, **kwargs)
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\shortcuts\prompt.py", line 282, in __init__
    output = output or get_default_output()
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\output\defaults.py", line 61, in get_default_output
    return create_output()
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\output\defaults.py", line 35, in create_output
    return Win32Output(stdout)
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\output\win32.py", line 83, in __init__
    info = self.get_win32_screen_buffer_info()
  File "c:\users\brandl\appdata\local\continuum\anaconda3\lib\site-packages\lineedit\deps\prompt_toolkit\output\win32.py", line 178, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```
So I'm afraid for some reason the prompt toolkit is not compatible with the IDE's console wrapper/emulator.
