### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by paulgioia** [holgerbrandl/r4intellij#54]
Just installed r4intellij plugin in PyCharm 4.5.3 (Windows 7). Displays R syntax correctly, but keep getting nullpointerexception:

null
java.lang.NullPointerException
    at com.intellij.ide.structureView.TextEditorBasedStructureViewModel.<init>(TextEditorBasedStructureViewModel.java:60)
    at com.r4intellij.psi.RScriptStructureViewFactory$RStructureViewModel.<init>(RScriptStructureViewFactory.java:75)
    at com.r4intellij.psi.RScriptStructureViewFactory$1.createStructureViewModel(RScriptStructureViewFactory.java:51)
    at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
    at com.intellij.ide.impl.StructureViewWrapperImpl.rebuild(StructureViewWrapperImpl.java:315)
    at com.intellij.ide.impl.StructureViewWrapperImpl$6.run(StructureViewWrapperImpl.java:253)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2350)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:266)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by holgerbrandl** [comment]
Same for me. It seem to happen in all but Intellij IDEA itself. Since I have no clue why the platforms differ, I've filed a request https://devnet.jetbrains.com/thread/466378 . Let's wait what they say.

Sorry for inconvenience.

**Comment by holgerbrandl** [comment]
closing because was not reported again.
