### ISSUE TITLE
NPE when starting IntelliJ (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by PioBeat** [holgerbrandl/r4intellij#76]
This Exception occurred when I was startubg IntelliJ (Version 2016.3.4 Ultimate)

java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.r4intellij.misc.rinstallcache.CachingUtils.evalRInternal(CachingUtils.java:123)
	at com.r4intellij.misc.rinstallcache.CachingUtils.evalRCmd(CachingUtils.java:89)
	at com.r4intellij.misc.rinstallcache.LibraryIndexFactory.updateIndex(LibraryIndexFactory.java:86)
	at com.r4intellij.misc.rinstallcache.LibraryIndexFactory.getLibraryCache(LibraryIndexFactory.java:77)
	at com.r4intellij.misc.rinstallcache.PackageCacheService$1.run(PackageCacheService.java:38)
Caused by: java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at com.r4intellij.misc.rinstallcache.CachingUtils.evalRInternal(CachingUtils.java:106)
	... 4 more

**Comment by holgerbrandl** [comment]
Thanks for the report. I hope to push out a new release later this week where the issue will be fixed.

**Comment by PioBeat** [comment]
Thank you for your efforts.

**Comment by holgerbrandl** [comment]
fixed in v1.0
