### ISSUE TITLE
UncheckedIOException: AccessDeniedException: /usr/lib/ssl/private

### ISSUE THREAD

**Issue by pokulo** [holgerbrandl/r4intellij#79]
I can't tell why, but your plug in tries to iterate over parts of my file tree which is better not to be accessed by user regular user level applications: The directory containing my private SSL-Keys /usr/lib/ssl/private. Since access to such directories is denied (on purpose of privacy) for my standard user, your plugin should handle such Situations.

The the call stack.
```
Worker exited due to exception: java.nio.file.AccessDeniedException: /usr/lib/ssl/private
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /usr/lib/ssl/private
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.r4intellij.interpreter.RInterpreterUtil.findScript(RInterpreterUtil.java:90)
	at com.r4intellij.interpreter.RInterpreterUtil.getInstallationFromPaths(RInterpreterUtil.java:63)
	at com.r4intellij.interpreter.RInterpreterUtil.suggestHomePaths(RInterpreterUtil.java:47)
	at com.r4intellij.interpreter.RInterpreterUtil.suggestHomePath(RInterpreterUtil.java:33)
	at com.r4intellij.settings.RSettings.<init>(RSettings.java:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:228)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at com.r4intellij.settings.RSettings.getInstance(RSettings.java:20)
	at com.r4intellij.packages.RSkeletonGenerator.getSkeletonsPath(RSkeletonGenerator.java:176)
	at com.r4intellij.packages.RIndexCache.getLibIndexFile(RIndexCache.java:210)
	at com.r4intellij.packages.RIndexCache.loadSkeletonCache(RIndexCache.java:60)
	at com.r4intellij.packages.RIndexCache.getInstance(RIndexCache.java:47)
	at com.r4intellij.psi.references.RResolver.addFromSkeletonsAndRLibrary(RResolver.java:42)
	at com.r4intellij.psi.references.RResolver.resolveInFileOrLibrary(RResolver.java:328)
	at com.r4intellij.psi.references.RResolver.resolveFunctionCall(RResolver.java:274)
	at com.r4intellij.psi.references.RReferenceImpl.multiResolve(RReferenceImpl.java:57)
	at com.r4intellij.psi.references.RReferenceImpl.resolve(RReferenceImpl.java:99)
	at com.r4intellij.psi.references.RReferenceImpl.resolve(RReferenceImpl.java:93)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:621)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:520)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at 
com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.AccessDeniedException: /usr/lib/ssl/private
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
	... 62 more
```

**Comment by holgerbrandl** [comment]
It did so to detect your R installation path. It won't do anymore in the updated version which is already available (just refresh plugins in iJ and install the update). 

As you can see in https://github.com/holgerbrandl/r4intellij/commit/913dfacc6e9f5fdf21a76f7c315b6a27a610e532#diff-14fc49d5bb2a67f07b3c608eeefdcb46R55 it now just checks a list of predefined common R locations to guess the installation path.

Feel welcome if you run into further issues.
