### ISSUE TITLE
Help server fails to start

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/r4intellij#81]
Reported by pokulo for PyCharm 2017.1

```
null
java.lang.AssertionError
	at com.r4intellij.documentation.RDocumentationProvider.generateDoc(RDocumentationProvider.java:193)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:659)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:656)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by holgerbrandl** [comment]
@pokulo This error occurred because the plugin somehow failed to start an instance of the R help server. Could you run
```
 R --vanilla --quiet --slave -e "cat(tools::startDynamicHelp(start = TRUE)); Sys.sleep(3600)"
```
in a terminal and report back the output?

**Comment by pokulo** [comment]
Ah, yes, R was indeed missing ;) I only intended to use this plug-in for code inspection and syntax-highlighting, did not try to run those scripts on my own PC, but sure R is needed ;)

This Exception doesn't appear any more. Other do :( But in another Issue ;)

**Comment by holgerbrandl** [comment]
In fact R should not be needed, even if many features (like package completions support, help) won't work without. 
I'll make sure that it ignores a missing R more gracefully.

**Comment by holgerbrandl** [comment]
The next version will also show an info box if the interpreter is not set
![image](https://cloud.githubusercontent.com/assets/200952/25219836/fd5f9bc6-25af-11e7-935a-5cf078f5341c.png)

**Comment by holgerbrandl** [comment]
Please update to v1.0.3 (by running ""Check for updates..." in PyCharm) which contains the patch for this ticket.
