### ISSUE TITLE
Plugin stopped working once I upgraded to Intellij 2016.3.6

### ISSUE THREAD

**Issue by dgivoli** [holgerbrandl/r4intellij#85]
Failed to generate skeleton for 'tools'. Exit code: 1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:263)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:263)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pokulo** [comment]
We just discussed this exceptions in #82. Duplicate?

**Comment by dgivoli** [comment]
Probably. Although it didn't happen to me until I moved to 2016.3.6, I don't know if that's the case with #82

**Comment by pokulo** [comment]
Not exactly, but you can try to follow our reasoning there, and test the compatibility of the Rscript [skeletonize_package.R](https://github.com/holgerbrandl/r4intellij/blob/master/r-helpers/skeletonize_package.R) with your current version of R.

**Comment by pokulo** [comment]
Which Version of R do you have? The issue in #82 was due to version incompatibilities of the current r4intellij (1.0.2) with an old version of R (3.2.3). See this [comment](https://github.com/holgerbrandl/r4intellij/issues/82#issuecomment-295740924).

**Comment by dgivoli** [comment]
It's 3.2.3 indeed.
How do I patch the skeletonize_package.R?
Or, can I just re-install the plugin with the fix from within intellij?

**Comment by holgerbrandl** [comment]
Please update to v1.0.3 (by running ""Check for updates..." in PyCharm) which contains the patch for this ticket.

**Comment by dgivoli** [comment]
Thanks
