### ISSUE TITLE
Failed to generate skeleton; file being used by another process

### ISSUE THREAD

**Issue by Mikuana** [holgerbrandl/r4intellij#86]
I'm getting errors whenever I open PyCharm with this plugin enabled. PyCharm attempts to build the skeletons and indexes, but I get 50+ error messages like the one below

> Failed to generate skeleton for '[package]' due to io issue: ...[package skeleton file references]...The process cannot access the file because it is being used by another process.

**Comment by holgerbrandl** [comment]
Could provide the full stacktrace for one of the errors?

**Comment by holgerbrandl** [comment]
Also what is your operating system?

**Comment by Mikuana** [comment]
Windows 7 Enterprise 64-bit

```
Failed to generate skeleton for 'datasets' due to io issue: C:\Users\cboyd\AppData\Local\Temp\r4j_skel_datasets_845161764568953133.R -> C:\Users\cboyd\.PyCharm2017.1\system\r_skeletons\1636418232\datasets.R: The process cannot access the file because it is being used by another process.

java.nio.file.FileSystemException: C:\Users\cboyd\AppData\Local\Temp\r4j_skel_datasets_845161764568953133.R -> C:\Users\cboyd\.PyCharm2017.1\system\r_skeletons\1636418232\datasets.R: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by holgerbrandl** [comment]
Thanks, I'll release a patched version later today.

**Comment by holgerbrandl** [comment]
Please update to v1.0.3 (by running "Check for updates..." in PyCharm) which contains the patch for this ticket.
