### ISSUE TITLE
Java Exception in R Language Support

### ISSUE THREAD

**Issue by paraboxx** [holgerbrandl/r4intellij#88]
Failed to generate skeleton for 'translations'. Exit code: 1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by PikalaxALT** [comment]
I'm getting a very similar error in PyCharm 2017.1.1, R4IntelliJ 1.0.4, on macOS Sierra version 10.12.4 (16E195):

    Failed to generate skeleton for 'tcltk'. Exit code: 1
    java.lang.Throwable
    	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:268)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by programata** [comment]
I'm also getting a quite similar error in intellij on macOS

Failed to generate skeleton for 'rJava'. Exit code: 1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment]
@programata Can you load rJava in R (`require(rJava)` without any issues? I could imagine that you're affected by http://stackoverflow.com/questions/34971966/how-does-one-configure-rjava-on-osx-to-select-the-right-jvm-jinit-failing. If yes, what would be an appropriate behavior of the plugin? Should it silently ignore a flawed package installation? i'm still unsure about what to do here.

**Comment by holgerbrandl** [comment]
@paraboxx Is `translations` bundled with R? If so why can't it be loaded with `require`? Can you load it. It does not seem to be  available via cran, but it seems to exist https://stat.ethz.ch/R-manual/R-devel/library/translations.

**Comment by holgerbrandl** [comment]
@PikalaxALT I can build a skeleton for version v3.4.0 of tckl under ubuntu. But it does not seem to be available for macos (via cran at least), did you do some custom R compilation?

**Comment by holgerbrandl** [comment]
@ PikalaxALT To separate the problems into different threads, we'll discuss 'tcltk' in the dedicated ticket #89.

**Comment by programata** [comment]
Thinking on it i realized that current behavior is ok. IMHO you can close
this issue

BR
Rafael

**Comment by paraboxx** [comment]
@holgerbrandl It seems something is indeed wrong with the package. Requiring it manually gives me "package translations does not have a namespace and should be re-installed". Reinstalling yields "package ‘translations’ is not available (for R version 3.4.0)". The first error suggests that the package has not been updated for R 3.4 yet but somehow R has been shipped with it.

**Comment by paraboxx** [comment]
[Even more interesting ](https://stackoverflow.com/questions/8012596/error-with-asreml-d-package-in-r-2-14-0/8014357#8014357) It seems like this requirement for a package namespace exists since R 2.14 already.
