### ISSUE TITLE
Exception while viewing quick-doc

### ISSUE THREAD

**Issue by kassak** [holgerbrandl/r4intellij#90]
Just viewed javadoc on table in DataGrip, with installed plugin.

```
java.lang.NullPointerException
	at com.r4intellij.documentation.RDocumentationProvider.isLibraryElement(RDocumentationProvider.java:379)
	at com.r4intellij.documentation.RDocumentationProvider.detectPackage(RDocumentationProvider.java:328)
	at com.r4intellij.documentation.RDocumentationProvider.getUrlFor(RDocumentationProvider.java:94)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.hasUrlsFor(CompositeDocumentationProvider.java:247)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.hasDocumentationFor(CompositeDocumentationProvider.java:213)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector$2.compute(DocumentationManager.java:1127)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector$2.compute(DocumentationManager.java:1122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:954)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.getDocumentation(DocumentationManager.java:1121)
	at com.intellij.codeInsight.documentation.DocumentationManager.lambda$doFetchDocInfo$6(DocumentationManager.java:719)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:224)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by holgerbrandl** [comment]
Is it a reproducible error? What it an R-script, scratch, an embedded language snippet, or some other context? Do you use v1.0.4 of the plugin?

**Comment by kassak** [comment]
@holgerbrandl Sorry, missed your comment :)
That actually was quick doc on table in DataGrip. Looks like you need to add check if it R's psi element
