### ISSUE TITLE
NoSuchMethodError: com.r4intellij.lang.parser.GrammarParserUtil.enter_section_

### ISSUE THREAD

**Issue by jackwwv** [holgerbrandl/r4intellij#91]
com.r4intellij.lang.parser.GrammarParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;

com.r4intellij.lang.parser.GrammarParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;
java.lang.NoSuchMethodError: com.r4intellij.lang.parser.GrammarParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;
	at com.r4intellij.lang.parser.RParser.document(RParser.java:148)
	at com.r4intellij.lang.parser.RParser.parse_root_(RParser.java:74)
	at com.r4intellij.lang.parser.RParser.parseLight(RParser.java:67)
	at com.r4intellij.lang.parser.RParser.parse(RParser.java:23)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:763)
	at com.r4intellij.editor.RFoldingBuilder.touchTree(RFoldingBuilder.java:85)
	at com.r4intellij.editor.RFoldingBuilder.buildFoldRegions(RFoldingBuilder.java:73)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:90)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:265)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:250)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:239)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditorAsync(PsiAwareTextEditorProvider.java:61)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:780)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:738)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$8.run(FileEditorManagerImpl.java:718)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:715)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:656)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:146)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14.run(FileEditorManagerImpl.java:1076)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1072)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:152)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:138)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:134)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:121)
	at com.intellij.openapi.fileEditor.impl.text.FileDropHandler.a(FileDropHandler.java:75)
	at com.intellij.openapi.fileEditor.impl.text.FileDropHandler.handleDrop(FileDropHandler.java:57)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$MyTransferHandler.importData(EditorsSplitters.java:777)
	at javax.swing.TransferHandler.importData(TransferHandler.java:827)
	at javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1544)
	at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
	at javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1282)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:545)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:859)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:783)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4736)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4611)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4457)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jackwwv** [comment]
win7 intellj14.0.3 java version "1.8.0_31"

**Comment by holgerbrandl** [comment]
Oh cool a parser bug ;-). Unfortunately there's little we can do about it unless you would be willing to share a (cut-down to the relevant bits) code sample that would allow us to reproduce this error. Would this be possible for you?

If you don't want to post it publicly you could also sent it to me via email.

**Comment by jackwwv** [comment]
platform:
R x64 3.3.3
win7
java version "1.8.0_31"
IDE:pycharm 4.5.3 or intellj idea 14.0.3
 
the error log I package send to you,








At 2017-04-25 23:49:54, "Holger Brandl" <notifications@github.com> wrote:


Oh cool a parser bug ;-). Unfortunately there's little we can do about it unless you would be willing to share a (cut-down to the relevant bits) code sample that would allow us to reproduce this error. Would this be possible for you?

If you don't want to post it publicly you could also sent it to me via email.

**Comment by jackwwv** [comment]
pycharm2016 is ok.





At 2017-04-25 23:49:54, "Holger Brandl" <notifications@github.com> wrote:


Oh cool a parser bug ;-). Unfortunately there's little we can do about it unless you would be willing to share a (cut-down to the relevant bits) code sample that would allow us to reproduce this error. Would this be possible for you?

If you don't want to post it publicly you could also sent it to me via email.

**Comment by holgerbrandl** [comment]
The plugin does not support versions before 2016.3. Sorry for inconvenience. 

Do you know @ktisha what `since-build` value would need to be used in the [plugin.xml](https://github.com/holgerbrandl/r4intellij/blob/master/META-INF/plugin.xml) to prevent users with older version from installing the plugin?
