### ISSUE TITLE
IndexOutOfBoundsException loading plugin

### ISSUE THREAD

**Issue by misea** [holgerbrandl/r4intellij#99]
I get the following exception loading the plugin. I have the plugin enabled, but the project has no R files and I am not using the extension. 

IntelliJ build: IntelliJ IDEA 2017.1.2 Build #IU-171.4249.39 
Plugin Version: 1.0.5

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:146)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:158)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:54)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)

**Comment by holgerbrandl** [comment]
What is your version of R?

Could you run 
```
wget https://raw.githubusercontent.com/holgerbrandl/r4intellij/master/r-helpers/package_versions.r
R -f package_versions.r
```
and attach the output to this ticket?

**Comment by zagorulkinde** [comment]
Hey! The same issue here.
R-3.4.0 version.

**Comment by holgerbrandl** [comment]
Could you @zagorulkinde run the R bits shown above and attach the output to this ticket. This would enable to progress with the ticket.

**Comment by zagorulkinde** [comment]
@holgerbrandl 

[1] "--- [1] SETTING PATH TO RTOOLS ---"
[1] "--- [2] SETTING ENV. VARIABLES TO ORACLE STANDALONE DRIVERS (oracle instant client) ---"
[1] "--- [3] SETTING JAVA_HOME ---"
> # library(tools)
> 
> versions = as.data.frame(installed.packages()[, c("Package", "Version")])
> 
> with(versions, cat(paste(Package, Version, sep = "\t"), sep = "\n"))
base	3.4.0
boot	1.3-19
class	7.3-14
cluster	2.0.6
codetools	0.2-15
colorspace	1.3-2
compiler	3.4.0
data.table	1.10.4
datasets	3.4.0
DBI	0.6-1
dichromat	2.0-0
digest	0.6.12
doParallel	1.0.10
foreach	1.4.3
foreign	0.8-67
ggplot2	2.2.1
graphics	3.4.0
grDevices	3.4.0
grid	3.4.0
gtable	0.2.0
iterators	1.0.8
jsonlite	1.4
KernSmooth	2.23-15
labeling	0.3
lattice	0.20-35
lazyeval	0.2.0
magrittr	1.5
MASS	7.3-47
Matrix	1.2-9
methods	3.4.0
mgcv	1.8-17
microbenchmark	1.4-2.1
munsell	0.4.3
nlme	3.1-131
nnet	7.3-12
parallel	3.4.0
plyr	1.8.4
RColorBrewer	1.1-2
Rcpp	0.12.10
reshape2	1.4.2
rJava	0.9-8
RODBC	1.3-14
ROracle	1.3-1
rpart	4.1-11
SberDBUtil	0.1.0
SberPDVal	4.1.63
SberUtil	1.8.1
scales	0.4.1
spatial	7.3-11
splines	3.4.0
stats	3.4.0
stats4	3.4.0
stringi	1.1.5
stringr	1.2.0
survival	2.41-3
tcltk	3.4.0
tibble	1.3.0
tools	3.4.0
translations	3.4.0
utils	3.4.0
xlsx	0.5.7
xlsxjars	0.6.1
> 
>

**Comment by PioBeat** [comment]
Hello,
the same issue occurred when starting IntelliJ IDEA Ultimate 2017.1.4
Build #IU-171.4694.23

The output from the command above is attached.
[package-output.txt](https://github.com/holgerbrandl/r4intellij/files/1123896/package-output.txt)

**Comment by hauntingEcho** [comment]
I also have this issue whenever opening a project, regardless of whether or not it contains R code (although I have no projects which are purely R).
R version: 3.4.0 (2017-04-21), installed via homebrew on OSX
IntelliJ version: 2017.1.5 build \#IU-171.4694.70, built July 4 2017
plugin version 1.0.6

IntelliJ trace:
`
Index: 1, Size: 1
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:151)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:158)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:54)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

`R -f package_versions.r` from Terminal:
`

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin16.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> # library(tools)
> 
> versions = as.data.frame(installed.packages()[, c("Package", "Version")])
> 
> with(versions, cat(paste(Package, Version, sep = "\t"), sep = "\n"))
magrittr	1.5
randomForest	4.6-12
stringi	1.1.5
stringr	1.2.0
base	3.4.0
boot	1.3-19
class	7.3-14
cluster	2.0.6
codetools	0.2-15
compiler	3.4.0
datasets	3.4.0
foreign	0.8-67
graphics	3.4.0
grDevices	3.4.0
grid	3.4.0
KernSmooth	2.23-15
lattice	0.20-35
MASS	7.3-47
Matrix	1.2-9
methods	3.4.0
mgcv	1.8-17
nlme	3.1-131
nnet	7.3-12
parallel	3.4.0
rpart	4.1-11
spatial	7.3-11
splines	3.4.0
stats	3.4.0
stats4	3.4.0
survival	2.41-3
tcltk	3.4.0
tools	3.4.0
utils	3.4.0
> 
> 

`

**Comment by holgerbrandl** [comment]
Please update to 1.0.7. I did not fix anything because I could not reproduce it. However the error should now include more details that will help to trace it down. So please reattach the extended error output to this ticket if the error happens again.

**Comment by hauntingEcho** [comment]
updating to R to 3.4.1_1 and the plugin to 1.0.7 removed the error message for me

**Comment by PioBeat** [comment]
Updating the plugin to 1.0.7 solved the problem. I have R version 3.2.3 installed.

**Comment by misea** [comment]
Sadly 1.0.7 did not solve this problem for me. Only line number changed
```
Index: 1, Size: 1
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:154)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:158)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:54)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Package versions:
```
assertthat	0.2.0
base	3.3.3
BH	1.62.0-1
bindr	0.1
bindrcpp	0.2
bitops	1.0-6
boot	1.3-18
broom	0.4.2
cellranger	1.1.0
class	7.3-14
cluster	2.0.5
codetools	0.2-15
colorspace	1.3-2
compiler	3.3.3
curl	2.8.9000
datasets	3.3.3
devtools	1.13.2
dichromat	2.0-0
digest	0.6.12
dplyr	0.7.1
forcats	0.2.0
foreign	0.8-67
ggplot2	2.2.1
git2r	0.18.0
glue	1.1.1
graphics	3.3.3
grDevices	3.3.3
grid	3.3.3
gtable	0.2.0
haven	1.1.0
hms	0.3
httr	1.2.1
jsonlite	1.5
KernSmooth	2.23-15
labeling	0.3
lattice	0.20-34
lazyeval	0.2.0
lubridate	1.6.0
magrittr	1.5
MASS	7.3-45
Matrix	1.2-8
memoise	1.1.0
methods	3.3.3
mgcv	1.8-17
mime	0.5
mnormt	1.5-5
modelr	0.1.0
munsell	0.4.3
nlme	3.1-131
nnet	7.3-12
openssl	0.9.6
parallel	3.3.3
pkgconfig	2.0.1
plogr	0.1-1
plyr	1.8.4
psych	1.7.5
purrr	0.2.2.2
R6	2.2.2
RColorBrewer	1.1-2
Rcpp	0.12.11
RCurl	1.95-4.8
readr	1.1.1
readxl	1.0.0
rematch	1.0.1
reshape2	1.4.2
rlang	0.1.1
rpart	4.1-10
rstudioapi	0.6
rvest	0.3.2
scales	0.4.1
selectr	0.3-1
spatial	7.3-11
splines	3.3.3
stats	3.3.3
stats4	3.3.3
stringi	1.1.5
stringr	1.2.0
survival	2.40-1
tcltk	3.3.3
tibble	1.3.3
tidyr	0.6.3
tidyverse	1.1.1
tools	3.3.3
utils	3.3.3
whisker	0.3-2
withr	1.0.2
XML	3.98-1.9
xml2	1.1.1
```

**Comment by holgerbrandl** [comment]
I've changed the error handling to make it more sensitive. Please try again once v1.0.8 is released.
